# Generated by Django 3.2.8 on 2022-07-09 22:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonusCode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('type', models.CharField(choices=[('Авто', 'Авто'), ('Ручн', 'Ручн')], max_length=6)),
                ('bonus_code', models.CharField(max_length=15, unique=True)),
                ('code_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='users.user_new')),
                ('code_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='users.user_new')),
            ],
            options={
                'verbose_name_plural': 'Бонус-коды',
            },
        ),
    ]
