# Generated by Django 3.2.8 on 2022-07-09 22:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('UUID', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('file_id', models.CharField(default='0', max_length=120)),
                ('status', models.TextField(default='111', max_length=50)),
                ('pimeyes_status', models.SmallIntegerField(default=1)),
                ('findclone_status', models.SmallIntegerField(default=1)),
                ('obsh_status', models.SmallIntegerField(default=1)),
                ('type', models.CharField(choices=[('free', 'Бесплатная'), ('dop', 'Доп.'), ('money', '$')], max_length=5)),
                ('user_lvl', models.CharField(default='0', max_length=20)),
                ('result', models.CharField(default='0', max_length=120)),
                ('creation_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('last_update', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('logs', models.TextField(blank=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.user_new')),
            ],
            options={
                'verbose_name_plural': 'Таски',
            },
        ),
    ]
