# Generated by Django 3.2.8 on 2022-07-09 19:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bot', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('chat_id', models.BigIntegerField(default=0)),
                ('user_name', models.CharField(default='-', max_length=150)),
                ('text', models.CharField(default='-', max_length=250)),
                ('additional1', models.CharField(max_length=250)),
                ('additional2', models.CharField(max_length=250)),
                ('additional3', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name_plural': 'История',
            },
        ),
        migrations.CreateModel(
            name='User_new',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chat_id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(blank=True, max_length=32, null=True)),
                ('first_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(blank=True, max_length=256, null=True)),
                ('language_code', models.CharField(blank=True, help_text='Язык клиента взятый из профиля', max_length=8, null=True)),
                ('ref_code', models.CharField(blank=True, max_length=64, null=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('extraSearches', models.BigIntegerField(default=0)),
                ('reg_date', models.DateField(default=django.utils.timezone.now)),
                ('coment', models.CharField(blank=True, max_length=512)),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.userlevels')),
            ],
            options={
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
